### ISSUE TITLE
Android PPSSPP: could not find executable

### ISSUE THREAD

**Issue by d9k** [dbeef/spelunky-psp#144]
![Screenshot_2023-08-09-17-26-34-115_org ppsspp ppsspp](https://github.com/dbeef/spelunky-psp/assets/7331988/ec18b22e-275d-4c91-a6e0-ba369a79e7a0)

PPSSPP v1.15.4
spelunky-psp v0.5 (*.pbp)

**Comment by dbeef** [comment]
Please check if renaming the file to `EBOOT.PBP` fixes the problem.

**Comment by d9k** [comment]
Of course not:
![Screenshot_2023-08-09-23-12-45-746_org ppsspp ppsspp](https://github.com/dbeef/spelunky-psp/assets/7331988/6ed3e5dc-036e-4b16-9a1c-3b67674cf9bb)

**Comment by d9k** [comment]
Of course not:
![Screenshot_2023-08-09-23-14-16-762_org ppsspp ppsspp](https://github.com/dbeef/spelunky-psp/assets/7331988/5cd8f893-d9cc-4b2d-ad84-d35a3f48bd16)

**Comment by d9k** [comment]
I think *.pbp must be converted to *.bin with PSX2PSP
https://i12bretro.github.io/tutorials/0323.html

**Comment by dbeef** [comment]
Works well on desktop PPSSP without any changes.

**Comment by d9k** [comment]
@dbeef, would you like to convert game release to *.bin (*.iso) for Android devices?

Also Android PPSSPP has a great gamepad support.

**Comment by dbeef** [comment]
Sure, I can release both, it's just that I was sure the .PBP is enough. Give me an hour or two, need to get my Android out of a drawer and double check.

**Comment by dbeef** [comment]
![image](https://github.com/dbeef/spelunky-psp/assets/13459304/b3fe9266-6139-4ab7-9e99-28344e3b159e)
![image](https://github.com/dbeef/spelunky-psp/assets/13459304/73755617-9fa9-4914-9814-f20cd50e1ad2)
![image](https://github.com/dbeef/spelunky-psp/assets/13459304/2490605e-eab2-4203-9a54-0e48e3804c10)

v0.5, .PBP with PPSSPP directly from Google Play. Works regardless of SpelunkyPSP/EBOOT name.

**Comment by d9k** [comment]
@dbeef, thx!

Finally it worked for me too, I'm happy 😊

There is a bug, `*.pbp` must be discovered by PPSSPP from folder, not loaded as a single file.

**Comment by dbeef** [comment]
@d9k nice! 😄 let me know if you encounter any other problems.
